version: '2'
services:
  web:
    build: .
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - DATABASE_URL
      - HUB_API_TOKEN
      - INBOUND_EMAIL_DOMAIN
      - MANDRILL_KEY
      - OUTBOUND_EMAIL_DOMAIN
      - SLACK_WEBHOOK_URL
    links:
      - database
    ports:
      - 4000:4000
  database:
    image: convox/postgres
    ports:
      - 5432
    volumes:
      - /var/lib/postgresql/data
